=== remizero/qtrcp/com/vgvgs/resources/xsd/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="app"/>
        <xs:element ref="logger"/>
        <xs:element ref="systemtrayicon"/>
        <xs:element ref="splashscreen"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="app">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="applicationdisplayname"/>
        <xs:element ref="applicationhashkey"/>
        <xs:element ref="applicationname"/>
        <xs:element ref="applicationversion"/>
        <xs:element ref="organizationname"/>
        <xs:element ref="organizationdomain"/>
        <xs:element ref="showsplash"/>
        <xs:element ref="showtryicon"/>
        <xs:element ref="standalone"/>
        <xs:element ref="iconimage"/>
        <xs:element ref="mayorversion"/>
        <xs:element ref="minorversion"/>
        <xs:element ref="pathversion"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="applicationdisplayname" type="xs:string"/>
  <xs:element name="applicationhashkey" type="xs:string"/>
  <xs:element name="applicationname" type="xs:string"/>
  <xs:element name="applicationversion" type="xs:string"/>
  <xs:element name="organizationname" type="xs:string"/>
  <xs:element name="organizationdomain" type="xs:string"/>
  <xs:element name="showsplash">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="showtryicon">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="standalone">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="iconimage" type="xs:string"/>
  <xs:element name="mayorversion">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
     </xs:simpleType>
   </xs:element>
  <xs:element name="minorversion">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="pathversion">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="logger">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sender"/>
        <xs:element ref="sendername"/>
        <xs:element ref="addressee"/>
        <xs:element ref="addresseename"/>
        <xs:element ref="subject"/>
        <xs:element ref="smtpserver"/>
        <xs:element ref="port"/>
        <xs:element ref="user"/>
        <xs:element ref="password"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sender" type="xs:string"/>
  <xs:element name="sendername" type="xs:string"/>
  <xs:element name="addressee" type="xs:string"/>
  <xs:element name="addresseename" type="xs:string"/>
  <xs:element name="subject" type="xs:string"/>
  <xs:element name="smtpserver" type="xs:string"/>
  <xs:element name="port">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='1'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="user" type="xs:string"/>
  <xs:element name="password" type="xs:string"/>
  <xs:element name="systemtrayicon">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="systrayicon"/>
        <xs:element ref="systraytooltip"/>
        <xs:element ref="systrayduration"/>
        <xs:element ref="systraydefaultmessagetype"/>
        <xs:element ref="systraymessagetitle"/>
        <xs:element ref="systraymessagebody"/>
        <xs:element ref="showsystemtrayicon"/>
        <xs:element ref="minimizetosystemtrayicon"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="systrayicon" type="xs:string"/>
  <xs:element name="systraytooltip" type="xs:string"/>
  <xs:element name="systrayduration">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="systraydefaultmessagetype" type="xs:string"/>
  <xs:element name="systraymessagetitle" type="xs:string"/>
  <xs:element name="systraymessagebody" type="xs:string"/>
  <xs:element name="showsystemtrayicon">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="minimizetosystemtrayicon">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="splashscreen">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="imagesplash"/>
        <xs:element ref="messagebox"/>
        <xs:element ref="font"/>
        <xs:element ref="progressbar"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="imagesplash" type="xs:string"/>
  <xs:element name="messagebox">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="x"/>
        <xs:element ref="y"/>
        <xs:element ref="w"/>
        <xs:element ref="h"/>
        <xs:element ref="alignment"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="font">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="family"/>
        <xs:element ref="bold"/>
        <xs:element ref="size"/>
        <xs:element ref="stretch"/>
        <xs:element ref="color"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="progressbar">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="textvisible"/>
        <xs:element ref="textalignment"/>
        <xs:element ref="invertedappearance"/>
        <xs:element ref="x"/>
        <xs:element ref="y"/>
        <xs:element ref="w"/>
        <xs:element ref="h"/>
        <xs:element ref="orientation"/>
        <xs:element ref="textdirection"/>
        <xs:element ref="format"/>
        <xs:element ref="max"/>
        <xs:element ref="min"/>
        <xs:element ref="backgroundcolor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="x">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="y">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="w">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="h">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="alignment">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="1"/>
        <xs:enumeration value="2"/>
        <xs:enumeration value="4"/>
        <xs:enumeration value="8"/>
        <xs:enumeration value="20"/>
        <xs:enumeration value="40"/>
        <xs:enumeration value="80"/>
        <xs:enumeration value="100"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="family" type="xs:string"/>
  <xs:element name="bold">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="size">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="stretch">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="color" type="xs:hexBinary"/>
  <xs:element name="textvisible">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="textalignment">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="top"/>
        <xs:enumeration value="bottom"/>
        <xs:enumeration value="left"/>
        <xs:enumeration value="right"/>
        <xs:enumeration value="center"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="invertedappearance">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="orientation">
    <xs:simpleType>
      <xs:restriction base='xs:string'>
        <xs:enumeration value="V"/>
        <xs:enumeration value="v"/>
        <xs:enumeration value="H"/>
        <xs:enumeration value="h"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="textdirection">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="format">
    <xs:simpleType>
      <xs:restriction base='xs:string'>
        <xs:enumeration value="%p%"/>
        <xs:enumeration value="%v%"/>
        <xs:enumeration value="%m%"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="max">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='1'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="min">
    <xs:simpleType>
      <xs:restriction base='xs:integer'>
        <xs:minInclusive value='0'/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="backgroundcolor" type="xs:hexBinary"/>
</xs:schema>

=== remizero/qtrcp/com/vgvgs/resources/xml/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/remizero/Proyectos/Desarrollo/Qt/qtrcp/com/ecosoftware/resources/xsd/config.xsd">
  <app>
    <applicationdisplayname>Ecomoditor</applicationdisplayname>
    <applicationhashkey>a9cd0d49e19637c0fea893d12ac87f64</applicationhashkey>
    <applicationname>ecomoditor</applicationname>
    <applicationversion>1.0</applicationversion>
    <organizationname>Eco Software, C.A.</organizationname>
    <organizationdomain>https://www.ecosoftware.com.ve</organizationdomain>
    <showsplash>1</showsplash>
    <showtryicon>0</showtryicon>
    <standalone>0</standalone>
    <iconimage>icono.png</iconimage>
    <mayorversion>5</mayorversion>
    <minorversion>0</minorversion>
    <pathversion>0</pathversion>
  </app>
  <logger>
    <sender></sender>
    <sendername></sendername>
    <addressee></addressee>
    <addresseename></addresseename>
    <subject></subject>
    <smtpserver></smtpserver>
    <port></port>
    <user></user>
    <password></password>
  </logger>
  <systemtrayicon>
    <systrayicon>icono.png</systrayicon>
    <systraytooltip>Ecomoditor</systraytooltip>
    <systrayduration>10</systrayduration>
    <systraydefaultmessagetype>Information</systraydefaultmessagetype>
    <systraymessagetitle>Ecomoditor</systraymessagetitle>
    <systraymessagebody>Aplicación con SystemTrayIcon</systraymessagebody>
    <showsystemtrayicon>1</showsystemtrayicon>
    <minimizetosystemtrayicon>1</minimizetosystemtrayicon>
  </systemtrayicon>
  <splashscreen>
    <imagesplash>splash.png</imagesplash><!--Aquí coloque el nombre de la imagen que usará para este lanzador de aplicaciones. Puede utilizar imagenes de tipo GIF, JPG, BMP, PNG.-->
    <messagebox>
      <x>10</x>
      <y>253</y>
      <w>800</w>
      <h>14</h>
      <alignment>1</alignment>
    </messagebox>
    <font>
      <family>monospace</family>
      <bold>1</bold>
      <size>9</size>
      <stretch>125</stretch>
      <color>2a5c7e</color>
    </font>
    <progressbar>
      <textvisible>0</textvisible><!-- Indica si el texto interno de la barra de progreso será visible -->
      <textalignment>center</textalignment><!-- Puede ser top | bottom | left | right | center -->
      <invertedappearance>0</invertedappearance><!-- This property holds whether or not a progress bar shows its progress inverted (e.g. from right to left). -->
      <x>0</x><!-- Pocisión en el eje X de la barra de progreso -->
      <y>270</y><!-- Pocisión en el eje Y de la barra de progreso -->
      <w>800</w><!-- Ancho de la barra de progreso -->
      <h>3</h><!-- Altura de la barra de progreso -->
      <orientation>H</orientation><!-- This property holds the orientation of the progress bar. The orientation must be Qt::Horizontal (the default) or Qt::Vertical. -->
      <textdirection>0</textdirection><!-- This property holds the reading direction of the text for vertical progress bars. -->
      <format>%p%</format><!-- %p% - is replaced by the percentage completed. %v% - is replaced by the current value. %m% - is replaced by the total number of steps. -->
      <max>100</max><!-- Valor máximo que puede aceptar la barra de progreso -->
      <min>0</min><!-- Valor mínimo que puede aceptar la barra de progreso -->
      <backgroundcolor>2a5c7e</backgroundcolor><!-- Color a ser mostrado en la barra de progreso -->
    </progressbar>
  </splashscreen>
</settings>
